title: Prismatic Psychotherapy

author: Laurel Severns Guntzel

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
  Author's home: "https://prismatic-mn.com"

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

navigation:
  - text: "Home"
    url: "/"
#  - text: "About"
#    url: "/aboutme/"
  - text: "Contact"
    url: "/contact/"

social-network-links:
  email: "name@prismatic-mn.com"
  reddit: yourname
  linkedin: yourname
  telephone: +0000000000

rss-description: This website is a virtual proof that I'm awesome

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false

url-pretty: "prismatic-mn.com"
title-on-all-pages: true

feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

theme: "beautiful-jekyll"

date_format: "%B %-d, %Y"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
